### ISSUE TITLE
Not stable for SetRGB/temperature/brightness

### ISSUE THREAD

**Issue by ctangc5** [Gromina/node-red-contrib-yeelight#1]
adjust the temperature & brightness many times,  it will shows the error info "UnhandlePromiseRejectionWarning: Unhandled promise rejection (rejection id: xx) [object object]"
In addition, cannot right set correct color with "colour picker" node for SetRGB

**Comment by Gromina** [comment]
Thanks for report. Will dig into it  next week.

**Comment by ctangc5** [comment]
Hi. There is critical issue for yeelight IP address. For example, the yeelight connect AP and assigned 192.168.1.86, we can command yeelight. But the network is shutdown or AP is shutdown, the node-red will crash. I think the code should add exception function to handle the network issue.

BR,
Chris

**Comment by Gromina** [comment]
Could you try the latest version?

**Comment by ctangc5** [comment]
Dears,

I will try the latest version. Also find the node-red crash issue that is yeelight is offline or AP is shutdown. For example, the yeelight assigned by AP is 192.168.1.150, when AP shutdown or yeelight offline, the node-red crash and cannot running. I believe maybe should add exception handle the issue.


Best Regards,
Chris

发件人: Alexander Sorokin [mailto:notifications@github.com]
发送时间: 2017年12月4日 15:23
收件人: Gromina/node-red-contrib-yeelight <node-red-contrib-yeelight@noreply.github.com>
抄送: Chris Tang <Chris.JJ.Tang@jci.com>; Author <author@noreply.github.com>
主题: Re: [Gromina/node-red-contrib-yeelight] Not stable for SetRGB/temperature/brightness (#1)


Could you try the latest version?

**Comment by ctangc5** [comment]
Dears,

I test it by latest version but crash issue still exist. Attach crash graphic for reference.

[cid:image001.png@01D36D51.734310F0]


Best Regards,
Chris

发件人: Chris Tang
发送时间: 2017年12月4日 17:08
收件人: 'Gromina/node-red-contrib-yeelight' <reply@reply.github.com>; Gromina/node-red-contrib-yeelight <node-red-contrib-yeelight@noreply.github.com>
抄送: Author <author@noreply.github.com>
主题: 答复: [Gromina/node-red-contrib-yeelight] Not stable for SetRGB/temperature/brightness (#1)

Dears,

I will try the latest version. Also find the node-red crash issue that is yeelight is offline or AP is shutdown. For example, the yeelight assigned by AP is 192.168.1.150, when AP shutdown or yeelight offline, the node-red crash and cannot running. I believe maybe should add exception handle the issue.


Best Regards,
Chris

发件人: Alexander Sorokin [mailto:notifications@github.com]
发送时间: 2017年12月4日 15:23
收件人: Gromina/node-red-contrib-yeelight <node-red-contrib-yeelight@noreply.github.com<mailto:node-red-contrib-yeelight@noreply.github.com>>
抄送: Chris Tang <Chris.JJ.Tang@jci.com<mailto:Chris.JJ.Tang@jci.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [Gromina/node-red-contrib-yeelight] Not stable for SetRGB/temperature/brightness (#1)


Could you try the latest version?

**Comment by glennss** [comment]
I've also had the same issue, when the light is offline, i.e. power is switched off, node-red will crash. The light in this example is found at 192.168.30.49 but is offline:


`Dec  7 10:26:52 raspberrypi Node-RED[28092]: 7 Dec 10:26:52 - [red] Uncaught Exception:
Dec  7 10:26:52 raspberrypi Node-RED[28092]: 7 Dec 10:26:52 - Error: connect EHOSTUNREACH 192.168.30.49:55443
Dec  7 10:26:52 raspberrypi Node-RED[28092]: at Object.exports._errnoException (util.js:1020:11)
Dec  7 10:26:52 raspberrypi Node-RED[28092]: at exports._exceptionWithHostPort (util.js:1043:20)
Dec  7 10:26:52 raspberrypi Node-RED[28092]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
Dec  7 10:26:52 raspberrypi systemd[1]: nodered.service: main process exited, code=exited, status=1/FAILURE
Dec  7 10:26:52 raspberrypi systemd[1]: Unit nodered.service entered failed state.
Dec  7 10:26:52 raspberrypi systemd[1]: nodered.service holdoff time over, scheduling restart.
`

**Comment by ctangc5** [comment]
Hi,

Please find the "index.js" on C:\Users\xxxx\node_modules\yeelight2 and edit "//    this.emit('error', err);" on Line 45. I believe can solve the issue.

BR,
Chris

**Comment by glennss** [comment]
Thanks Chris, but nope, still the same issue

**Comment by ctangc5** [comment]
Hi,

I attach index.js file you can replace it on C:\Users\xxxx\node_modules\yeelight2

P.S. Please change the name index.bak to index.js firstly.

Best Regards,
Chris

发件人: glennss [mailto:notifications@github.com]
发送时间: 2017年12月12日 1:15
收件人: Gromina/node-red-contrib-yeelight <node-red-contrib-yeelight@noreply.github.com<mailto:node-red-contrib-yeelight@noreply.github.com>>
抄送: Chris Tang <Chris.JJ.Tang@jci.com<mailto:Chris.JJ.Tang@jci.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [Gromina/node-red-contrib-yeelight] Not stable for SetRGB/temperature/brightness (#1)


Thanks Chris, but nope, still the same issue

**Comment by GeeBee93** [comment]
Hey,

I can confirm the issue with SetRGB and Colour Picker. Already got the latest version of node-red-contrib-yeelight along with Colour Picker in "Format: hex" and it's just changing the color to blue, but no other color. 

Thank you for your help :)

**Comment by davehun** [comment]
its not crashing node-red for me with the current release version but if the bulb is offline at some point the module does not re connect when the bulb is brought back online

**Comment by ctangc5** [comment]
Dears,

With current release version still have issue which I find as follows,

[error] [yeelight-config:27cc284d.1735e8] ReferenceError: window is not define.



Best Regards,
Chris

发件人: David Hunninsett [mailto:notifications@github.com]
发送时间: 2018年1月12日 17:52
收件人: Gromina/node-red-contrib-yeelight <node-red-contrib-yeelight@noreply.github.com>
抄送: Chris Tang <Chris.JJ.Tang@jci.com>; Author <author@noreply.github.com>
主题: Re: [Gromina/node-red-contrib-yeelight] Not stable for SetRGB/temperature/brightness (#1)


its not crashing node-red for me with the current release version but if the bulb is offline at some point the module does not re connect when the bulb is brought back online
