### ISSUE TITLE
NodeRED Crash!!!

### ISSUE THREAD

**Issue by ma-gu-16** [Gromina/node-red-contrib-yeelight#13]
```
May 11 11:13:14 homematic-raspi daemon.err node-red: Yeelight error { Error: read ECONNRESET
May 11 11:13:14 homematic-raspi daemon.err node-red:     at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
May 11 11:13:14 homematic-raspi daemon.err node-red: 11 May 11:13:14 - [red] Uncaught Exception:
May 11 11:13:14 homematic-raspi daemon.err node-red: 11 May 11:13:14 - TypeError: this.error is not a function
May 11 11:13:14 homematic-raspi daemon.err node-red:     at Yeelight.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-yeelight/yeelight/yeelight.js:36:22)
May 11 11:13:14 homematic-raspi daemon.err node-red:     at Yeelight.emit (events.js:189:13)
May 11 11:13:14 homematic-raspi daemon.err node-red:     at Yeelight.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-yeelight/node_modules/yeelight2/index.js:45:10)
May 11 11:13:14 homematic-raspi daemon.err node-red:     at Socket.emit (events.js:189:13)
May 11 11:13:14 homematic-raspi daemon.err node-red:     at emitErrorNT (internal/streams/destroy.js:82:8)
May 11 11:13:14 homematic-raspi daemon.err node-red:     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
May 11 11:13:14 homematic-raspi daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:63:19)
May 11 11:13:14 homematic-raspi daemon.err node-red: Node-RED exited with non-zero exit status 1
```

**Comment by ma-gu-16** [comment]
more errors... cant use this node :(


```
May 11 11:16:26 homematic-raspi daemon.err node-red: (node:7225) UnhandledPromiseRejectionWarning: Error: timeout
May 11 11:16:26 homematic-raspi daemon.err node-red:     at Timeout._onTimeout (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-yeelight/node_modules/yeelight2/index.js:167:16)
May 11 11:16:26 homematic-raspi daemon.err node-red:     at ontimeout (timers.js:436:11)
May 11 11:16:26 homematic-raspi daemon.err node-red:     at tryOnTimeout (timers.js:300:5)
May 11 11:16:26 homematic-raspi daemon.err node-red:     at listOnTimeout (timers.js:263:5)
May 11 11:16:26 homematic-raspi daemon.err node-red:     at Timer.processTimers (timers.js:223:10)
May 11 11:16:26 homematic-raspi daemon.err node-red: (node:7225) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
May 11 11:16:26 homematic-raspi daemon.err node-red: (node:7225) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by andreypopov** [comment]
+1

**Comment by exdee85** [comment]
+1
YLDD04YL

**Comment by JohanPotgieter** [comment]
Agreed. I had to remove it for now.
