### ISSUE TITLE
Node-red crashes after yeelight connection error

### ISSUE THREAD

**Issue by skoxo** [Gromina/node-red-contrib-yeelight#17]
I'm successfully running a flow that controls my yeelight from a raspberry pi. However, when the node-red-contrib-yeelight node cannot connect to the yeelight (for example when the power of the light is switched off) the node generates an unhandled error that let's node-red crash and restart. This cycle then continues every minute or so.

Is there any way to catch this error and let the node try to connect to the yeelight again instead of crashing the whole system?

This is the terminal output of node-red:
```
6 Jun 23:07:23 - [info] Starting flows
Connecting to Flic Daemon at 127.0.0.1:5551
6 Jun 23:07:24 - [info] Started flows
Yeelight error Error: connect EHOSTUNREACH 192.168.2.85:55443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.2.85',
  port: 55443
}
6 Jun 23:07:41 - [red] Uncaught Exception:
6 Jun 23:07:41 - TypeError: this.error is not a function
    at Yeelight.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-yeelight/yeelight/yeelight.js:36:22)
    at Yeelight.emit (events.js:310:20)
    at Yeelight.<anonymous> (/home/pi/.node-red/node_modules/yeelight2/index.js:45:10)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 2.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
6 Jun 23:07:49 - [info]
Welcome to Node-RED
```

**Comment by PTS93** [comment]
The package on npm is I think outdated, maybe try installing it from git. This error was fixed before.

**Comment by SimonVanheukelom** [comment]
> 
> 
> The package on npm is I think outdated, maybe try installing it from git. This error was fixed before.

I ran into the same issue, but as i have changed multiple things at the same time, it took me a lot of time to arrive here.

I hope this will work :-) can you show me how to install from git ? thanks a lot

**Comment by PTS93** [comment]
hey the maintainer just updated the npm package, try re-installing. Although I notice that this issue seems to have multiple causes so it might not fix your specific issue.

**Comment by SimonVanheukelom** [comment]
> 
> 
> hey the maintainer just updated the npm package, try re-installing. Although I notice that this issue seems to have multiple causes so it might not fix your specific issue.

 i've just saw the issue done 9 days ago: #21 Publish new version to npm
the problem is that the nodered palette manage menu as this page : https://flows.nodered.org/node/node-red-contrib-yeelight
is on the 1.0.6 version :-S 
Using the "npm install node-red-contrib-yeelight" command of the npm page
https://www.npmjs.com/package/node-red-contrib-yeelight
worked thanks

now wait and see

**Comment by PTS93** [comment]
Weird, then try `npm install git+https://github.com/Gromina/node-red-contrib-yeelight.git` in your .node-red folder but maybe uninstall it first

**Comment by SimonVanheukelom** [comment]
sorry i wrote too fast
the command wrote something so i was happy but nothing is installed ...

npm i node-red-contrib-yeelight
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ node-red-contrib-yeelight@1.0.7
updated 1 package and audited 146 packages in 4.779s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by SimonVanheukelom** [comment]
Ok ok,

i had to be in the nodered folder to tun the command: npm install node-red-contrib-yeelight
now it is ok, in the web page menu manage pallette 1.0.7 is installed

thanks a lot
