### ISSUE TITLE
Restarts node-red

### ISSUE THREAD

**Issue by nomadbeni** [Gromina/node-red-contrib-yeelight#2]
If the yeelight is offline and a command is sent to the device, it says: UnhandledPromiseRejection....... which is good, because the yeelight is offline.
But when the yeelight comes online, it restarts the node-red, which is not good.
I attached a screenshot of the message.
Once it continuously restarted node-red untill i stopped it and deleted the yeelight node in the command line.
![yeelight](https://user-images.githubusercontent.com/29810786/32628525-7a5e6f22-c596-11e7-88ec-b83f673161be.JPG)

**Comment by HendrikRoth** [comment]
+1
Same issue here.

**Comment by Gromina** [comment]
Thanks for report. Will try to fix it asap. But probably not earlier than on next week unless you make pull request. 
Busy at work :(

**Comment by mane-wt** [comment]
Hi,
I have a similiar problem. If the Yeelight is offline och the IP-adress have changed, Node-Red got stuck in a restart loop and even managed to crash the installation on my Raspberry Pi -> Reinstallation from scratch.
I got this from syslog:
![image](https://user-images.githubusercontent.com/30109811/33345642-55931e9e-d48d-11e7-853a-09a3a5a7e678.png)

**Comment by HendrikRoth** [comment]
Fixed the issue.

https://github.com/Gromina/node-red-contrib-yeelight/pull/3

**Comment by Gromina** [comment]
Could you please confirm that the latest version fixes the issue?

Thanks to @HendrikRoth who made the fix

**Comment by HendrikRoth** [comment]
The main fix was to wrap the method in an try/catch block. i updated to the latest version only to be up to date.

**Comment by nomadbeni** [comment]
Well
 I tried it. This happened: 

[yeelight error.txt](https://github.com/Gromina/node-red-contrib-yeelight/files/1528442/yeelight.error.txt)

**Comment by mane-wt** [comment]
Hi, I have also tried the new version and as long as the Yeelight bulb is online, everything works well but if I cut the power to the bulb the same behavior occurs as before with approximately 2 restarts
[syslog.txt](https://github.com/Gromina/node-red-contrib-yeelight/files/1531866/syslog.txt)
 of Node-Red per minute.
I enclose a new syslog that covers 3 restarts

**Comment by glennss** [comment]
Same issue for me :(

`Dec  7 10:26:52 raspberrypi Node-RED[28092]: 7 Dec 10:26:52 - [red] Uncaught Exception:
Dec  7 10:26:52 raspberrypi Node-RED[28092]: 7 Dec 10:26:52 - Error: connect EHOSTUNREACH 192.168.30.49:55443
Dec  7 10:26:52 raspberrypi Node-RED[28092]: at Object.exports._errnoException (util.js:1020:11)
Dec  7 10:26:52 raspberrypi Node-RED[28092]: at exports._exceptionWithHostPort (util.js:1043:20)
Dec  7 10:26:52 raspberrypi Node-RED[28092]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
Dec  7 10:26:52 raspberrypi systemd[1]: nodered.service: main process exited, code=exited, status=1/FAILURE
Dec  7 10:26:52 raspberrypi systemd[1]: Unit nodered.service entered failed state.
Dec  7 10:26:52 raspberrypi systemd[1]: nodered.service holdoff time over, scheduling restart.
`

**Comment by Gromina** [comment]
Could you please test 1.0.4 version in several  cases:

- starting node-red when yeelight is offline
- starting node-res when yeelight is online
- turning yeelight offline when node-red is running

I can't test it on hardware tight now :(

**Comment by nomadbeni** [comment]
I will test is on saturday and post the log.

**Comment by glennss** [comment]
Timing out and crashing :(

[syslog.txt](https://github.com/Gromina/node-red-contrib-yeelight/files/1556863/syslog.txt)

**Comment by mane-wt** [comment]
![image](https://user-images.githubusercontent.com/30109811/34013301-2b394768-e117-11e7-8d82-48645e74e353.png)
![image](https://user-images.githubusercontent.com/30109811/34013333-51451162-e117-11e7-846c-69099a903798.png)
![image](https://user-images.githubusercontent.com/30109811/34013386-9ddb8fa6-e117-11e7-9135-2e380f0b7680.png)

Unfortunately the flow that worked with 1.03 won't work with 1.04 for me :-(
I have rebboted the RPi, but same result.
The good news is thas Node-red won't restart anymore if a turn off the power to Yeelight.

**Comment by GeeBee93** [comment]
Same issue here, updating from 1.03 to 1.04 completely broke all nodes for me :(

**Comment by nomadbeni** [comment]
Same with me.
![image](https://user-images.githubusercontent.com/29810786/34082237-c98c6176-e35a-11e7-8cae-dd3eaf27e654.png)

**Comment by LolCatPhd** [comment]
Getting the same error as well. 
1.04 broke all nodes.

**Comment by mane-wt** [comment]
Any clues whats wrong?
